version: '3.7'

services:
  eureka-service:
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - eureka-service

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - eureka-service

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - eureka-service
      - user-service
      - auth-service

networks:
  microservices-network:
    driver: bridge
